-- ── Users ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                  VARCHAR(120)  NULL,
  email                 VARCHAR(190)  NOT NULL UNIQUE,
  password_hash         VARCHAR(255)  NOT NULL,
  profile_photo_base64  TEXT          NULL,
  created_at            TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at            TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_photo_base64   TEXT          NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at             TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_access_token    TEXT          NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_refresh_token   TEXT          NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_token_expiry    TEXT          NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_email           VARCHAR(190)  NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS expo_push_token        TEXT          NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gcal_channel_id        TEXT          NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gcal_watch_expiry      TEXT          NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role                   VARCHAR(20)   NOT NULL DEFAULT 'user';

-- ── Planner ───────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tasks (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title       VARCHAR(190)  NOT NULL,
  description TEXT          NULL,
  due_date    DATE          NULL,
  due_time    TIME          NULL,
  priority    VARCHAR(20)   NOT NULL DEFAULT 'medium',
  status      VARCHAR(20)   NOT NULL DEFAULT 'pending',
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_tasks_priority CHECK (priority IN ('low', 'medium', 'high')),
  CONSTRAINT chk_tasks_status   CHECK (status   IN ('pending', 'done'))
);

CREATE TABLE IF NOT EXISTS meetings (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          INTEGER       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title            VARCHAR(190)  NOT NULL,
  description      TEXT          NULL,
  meeting_date     DATE          NOT NULL,
  meeting_time     TIME          NOT NULL,
  duration_minutes INTEGER       NULL,
  location         VARCHAR(255)  NULL,
  status           VARCHAR(20)   NOT NULL DEFAULT 'scheduled',
  created_at       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_meetings_status CHECK (status IN ('scheduled', 'completed', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS meeting_participants (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id        INTEGER       NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
  participant_name  VARCHAR(120)  NULL,
  participant_email VARCHAR(190)  NOT NULL,
  created_at        TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_meeting_participant UNIQUE (meeting_id, participant_email)
);

CREATE TABLE IF NOT EXISTS events (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      INTEGER       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title        VARCHAR(190)  NOT NULL,
  description  TEXT          NULL,
  event_date   DATE          NOT NULL,
  event_time   TIME          NULL,
  location     VARCHAR(255)  NULL,
  event_type   VARCHAR(80)   NOT NULL DEFAULT 'general',
  gcal_event_id VARCHAR(255) NULL,
  created_at   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE events ADD COLUMN IF NOT EXISTS gcal_event_id VARCHAR(255) NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_events_user_gcal
  ON events (user_id, gcal_event_id)
  WHERE gcal_event_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS notes (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title      VARCHAR(190)  NOT NULL,
  content    TEXT          NULL,
  status     VARCHAR(20)   NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_notes_status CHECK (status IN ('active', 'archived'))
);

CREATE INDEX IF NOT EXISTS idx_tasks_user_status    ON tasks    (user_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_due_date       ON tasks    (due_date);
CREATE INDEX IF NOT EXISTS idx_meetings_user_date   ON meetings (user_id, meeting_date);
CREATE INDEX IF NOT EXISTS idx_meetings_status      ON meetings (status);
CREATE INDEX IF NOT EXISTS idx_events_user_date     ON events   (user_id, event_date);
CREATE INDEX IF NOT EXISTS idx_events_type          ON events   (event_type);
CREATE INDEX IF NOT EXISTS idx_notes_user_updated   ON notes    (user_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_notes_user_status    ON notes    (user_id, status);

-- ── Conversations ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS conversations (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title      VARCHAR(255)  NOT NULL DEFAULT 'Nueva conversación',
  created_at TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id INTEGER       NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  role            VARCHAR(20)   NOT NULL,
  content         TEXT          NOT NULL,
  intent          VARCHAR(100)  NULL,
  sentiment       VARCHAR(20)   NULL,
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);
