from __future__ import annotations

from app.db.postgresql.connector import get_db_cursor


def ensure_planner_tables() -> None:
    with get_db_cursor() as (connection, cursor):
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS tasks (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              title VARCHAR(190) NOT NULL,
              description TEXT NULL,
              due_date DATE NULL,
              due_time TIME NULL,
              priority VARCHAR(20) NOT NULL DEFAULT 'medium',
              status VARCHAR(20) NOT NULL DEFAULT 'pending',
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT chk_tasks_priority CHECK (priority IN ('low', 'medium', 'high')),
              CONSTRAINT chk_tasks_status CHECK (status IN ('pending', 'in_progress', 'done'))
            );
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS meetings (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              title VARCHAR(190) NOT NULL,
              description TEXT NULL,
              meeting_date DATE NOT NULL,
              meeting_time TIME NOT NULL,
              duration_minutes INTEGER NULL,
              location VARCHAR(255) NULL,
              status VARCHAR(20) NOT NULL DEFAULT 'scheduled',
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT chk_meetings_status CHECK (status IN ('scheduled', 'completed', 'cancelled'))
            );
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS meeting_participants (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              meeting_id INTEGER NOT NULL REFERENCES meetings(id) ON DELETE CASCADE,
              participant_name VARCHAR(120) NULL,
              participant_email VARCHAR(190) NOT NULL,
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT uq_meeting_participant UNIQUE (meeting_id, participant_email)
            );
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS events (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              title VARCHAR(190) NOT NULL,
              description TEXT NULL,
              event_date DATE NOT NULL,
              event_time TIME NULL,
              location VARCHAR(255) NULL,
              event_type VARCHAR(80) NOT NULL DEFAULT 'general',
              gcal_event_id VARCHAR(255) NULL,
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            """
        )
        cursor.execute(
            "ALTER TABLE events ADD COLUMN IF NOT EXISTS gcal_event_id VARCHAR(255) NULL;"
        )
        cursor.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS uq_events_user_gcal
            ON events (user_id, gcal_event_id)
            WHERE gcal_event_id IS NOT NULL;
            """
        )

        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS notes (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              title VARCHAR(190) NOT NULL,
              content TEXT NULL,
              status VARCHAR(20) NOT NULL DEFAULT 'active',
              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
              CONSTRAINT chk_notes_status CHECK (status IN ('active', 'archived'))
            );
            """
        )

        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_tasks_user_status ON tasks (user_id, status);"
        )
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks (due_date);")
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_meetings_user_date ON meetings (user_id, meeting_date);"
        )
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_meetings_status ON meetings (status);")
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_events_user_date ON events (user_id, event_date);"
        )
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_events_type ON events (event_type);")
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_notes_user_updated ON notes (user_id, updated_at);"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_notes_user_status ON notes (user_id, status);"
        )

        connection.commit()
